version: "3.8"
services:
  db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: headless_gacha_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data/pgdata
